export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const CREATE_AUDIO_CONTEXT = 'CREATE_AUDIO_CONTEXT'

export const CONNECT_MICROPHONE_REQUEST = 'CONNECT_MICROPHONE_REQUEST'
export const CONNECT_MICROPHONE_SUCCESS = 'CONNECT_MICROPHONE_SUCCESS'
export const CONNECT_MICROPHONE_FAILURE = 'CONNECT_MICROPHONE_FAILURE'
