export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

// Mixer
export const CREATE_AUDIO_CONTEXT = 'CREATE_AUDIO_CONTEXT'

export const CONNECT_MICROPHONE_REQUEST = 'CONNECT_MICROPHONE_REQUEST'
export const CONNECT_MICROPHONE_SUCCESS = 'CONNECT_MICROPHONE_SUCCESS'
export const CONNECT_MICROPHONE_FAILURE = 'CONNECT_MICROPHONE_FAILURE'

export const DISCONNECT_MICROPHONE = 'DISCONNECT_MICROPHONE'

export const CONNECT_AUDIO_BUFFER_REQUEST = 'CONNECT_AUDIO_BUFFER_REQUEST'
export const CONNECT_AUDIO_BUFFER_SUCCESS = 'CONNECT_AUDIO_BUFFER_SUCCESS'
export const CONNECT_AUDIO_BUFFER_FAILURE = 'CONNECT_AUDIO_BUFFER_FAILURE'

// Scrubber
export const SEEK_PLAYBACK_START = 'SEEK_PLAYBACK_START'

// Tracker
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE'

// Transport
export const RESUME_PLAYBACK = 'RESUME_PLAYBACK'
export const PAUSE_PLAYBACK = 'PAUSE_PLAYBACK'
